name: tobeto_pair_one
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  cloud_firestore: ^4.15.4
  firebase_auth: ^4.17.4
  firebase_core: ^2.25.4
  firebase_storage: ^11.6.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  
  image_picker: ^1.0.7
  shared_preferences: ^2.2.2
  video_compress: ^3.1.2
  video_player: ^2.8.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
